#开发配置
server:
  port: 8080
  session:

#上传路径
web:
  upload-path: /Users/lu/Desktop

spring:
  profiles: dev

  datasource:
    url: jdbc:oracle:thin:@192.168.6.205:1521:orcl
    username: test
    password: test
    driver-class-name: oracle.jdbc.driver.OracleDriver
    druid.initialSize: 5
    druid.maxActive: 100
    druid.minIdle: 10
    druid.maxWait: 60000
     #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  mvc:
    #静态资源过滤
    static-path-pattern: /**

  #################redis基础配置#################
  application:
    name: spring-boot-redis
  redis:
    database: 0
    ip: 192.168.6.205
    pwd:
    port: 6379
    # 连接超时时间 单位 ms（毫秒）
    timeout: 20000
    #cluster:
      #nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
      #maxRedirects: 6

    #################redis线程池设置#################
    # 连接池中的最大空闲连接，默认值也是8。
    pool:
      maxIdle:  150
      #连接池中的最小空闲连接，默认值也是0。
      minIdle: 100
      # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      maxActive: 1024
      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
      max-wait: 1000
      #多长时间检查一次连接池中空闲的连接
      maxTotal: 150
      #当池内没有返回对象时，最大等待时间
      maxWait: 7000
      #当调用borrowObject方法时，是否进行有效性检查
      testOnBorrow: true
      #重新连接重试次数
      reconnectRetryCount: 50
      #重连等待时间
      reconnectRetryWaittime: 7000



#分页的配置
pagehelper:
    helperDialect: oracle
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    offset-as-page-num: true
    row-bounds-with-count: true


